### ISSUE TITLE
Links on Nextcloud App Store not working

### ISSUE THREAD

**Issue by Co0p3r21** [e-alfred/nextcloud-printer#1]
The Links in the Nextcloud App Store to this Project are not correct. 
https://apps.nextcloud.com/apps/printer

**Comment by e-alfred** [comment]
The links seem to work fine (I use Github releases for this purpose).

**Comment by Co0p3r21** [comment]
You are mostly right. I cant´t remember but now I just see that the Homepage Link is wrong.
It links to https://github.com/e.alfred/nextcloud-printer/ not https://github.com/e-alfred/nextcloud-printer/

**Comment by werdahias** [comment]
He is right, though.

**Comment by gergelypolonkai** [comment]
This should be re-opened, as the resource links on the [addon page](https://apps.nextcloud.com/apps/printer) are wrong:

- Homepage: https://github.com/e.alfred/nextcloud-printer/
- User documentation: https://github.com/westberliner/owncloud-checksum/blob/master/README.md
- Admin documentation: https://github.com/westberliner/owncloud-checksum/blob/master/README.md

The home-page is wrong (`e.alfred` instead of `e-alfred` in the link), and the documentation links point to a completely different addon.

**Comment by e-alfred** [comment]
Sorry for the delay, the links are fixed now and a new release will be released soon.
